### PR TITLE
Added third party dependencies for linux support and suppressed warnings

### PR DESCRIPTION
**Pull request by chris-gong**
I added a Linux folder with the necessary .dll, .lib, and .so files to compile the client sdk for linux. I have made a video about [this](https://youtu.be/48P4fjLP1vU). To actually deploy a linux server to gamelift, you'll still need to build some other .so files that the client sdk also depend on. However, I also cover this in the video. Note that I have not confirmed that this works when running a client project/game on a Linux machine. This solution was mainly meant for cross compiling Linux from a Windows computer (Windows clients playing on Linux servers work), so if anyone could test the client on a Linux device, that would be appreciated.

Lastly, in the future, would you be open to accepting a pull request for a script that installs the third party .dll, .lib, and .so files instead of keeping them in the repository? Only reason I say this is because I am not sure if it is generally good practice to keep these third party dependencies in the repo. I can probably do a batch script for windows, and possibly a shell script for linux to do this kind of job. Great job on the repository thus far, plan to use it for more tutorials in the future :)

### CODE REVIEW

**Comment by chris-gong** [comment]
Added some small statements to suppress some warnings as well. I'm currently on Unreal version 4.22.2

**Comment by chris-gong** [comment]
Modified CreatePlayerSession to return status as well. Also, added methods for creating game session placements for queues, describing game session placements for queues, describing game session queues for getting fleets associated with the queue based on the region code, and searching for game sessions associated with a specific fleet. Note that queues are needed to use spot fleets, which are cheaper than on-demand fleets.

**Comment by YetiTechStudios** [comment]
Hi @chris-gong 

Thank you for the pull request. We will merge this change but before that could you please update the `VersionName` in `uplugin` file with whatever version of aws you compiled.

**Comment by chris-gong** [comment]
Hey @YetiTechStudios really sorry about the delay, I will try to get on this as soon as possible.

**Comment by chris-gong** [comment]
Hey @YetiTechStudios, the pull request should be ready now! I may make additionalchanges in the near future to the readme, but I believe it's good now (versionname and binaries are updated).

**Comment by chris-gong** [comment]
Hi @ryanjon2040, tagging you just in case you're not receiving the notifications.

**Comment by YetiTechStudios** [comment]
Thank you @chris-gong I've merged this pull request to master branch.

**Pull request merged**
